#!/usr/bin/env node

/**
 * Bootstraps a local Supabase instance for development.
 *
 * 1. Checks that Docker is running and `supabase` CLI is installed.
 * 2. Starts Supabase local containers (runs migrations + seed automatically).
 * 3. Reads the printed credentials and writes .env.local so Next.js can connect.
 */

import { execSync, spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENV_LOCAL = resolve(ROOT, '.env.local');

function run(cmd, opts = {}) {
  return spawnSync(cmd, { shell: true, cwd: ROOT, encoding: 'utf-8', ...opts });
}

function fatal(msg) {
  console.error(`\n❌ ${msg}\n`);
  process.exit(1);
}

// ── Pre-flight checks ──────────────────────────────────────────────────────

const docker = run('docker info');
if (docker.status !== 0) {
  fatal(
    'Docker is not running. Please start Docker Desktop and try again.'
  );
}

const sbVersion = run('npx supabase --version');
if (sbVersion.status !== 0) {
  fatal(
    'Supabase CLI not found. Install it with:\n  npm i -g supabase\n  or: npx supabase --version'
  );
}

console.log('🐳 Docker is running');
console.log(`📦 Supabase CLI: ${sbVersion.stdout.trim()}`);

// ── Start Supabase ─────────────────────────────────────────────────────────

console.log('\n🚀 Starting Supabase local development stack...\n');

const start = run('npx supabase start', { stdio: 'inherit', timeout: 300_000 });

// supabase start may exit non-zero or print to stderr even on success,
// so we always check `supabase status` to determine actual state.

const status = run('npx supabase status', { stdio: 'pipe' });
if (status.status !== 0) {
  const hint = (start.stderr || start.stdout || '').trim();
  fatal(`Supabase failed to start.\n${hint}\n${status.stderr || ''}`);
}

const output = status.stdout;

function extract(label) {
  const re = new RegExp(`${label}\\s*│\\s*(.+?)\\s*│?\\s*$`, 'im');
  const m = output.match(re);
  return m ? m[1].trim() : null;
}

// CLI v2.101+ uses "Project URL" / "Publishable" / "Secret" / "Studio" / "Mailpit"
// Older CLIs use "API URL" / "anon key" / "service_role key" / "Studio URL" / "Inbucket URL"
const apiUrl = extract('Project URL') || extract('API URL');
const anonKey = extract('Publishable') || extract('anon key');
const serviceRoleKey = extract('Secret') || extract('service_role key');
const studioUrl = extract('Studio') || extract('Studio URL');
const mailUrl = extract('Mailpit') || extract('Inbucket URL');

if (!apiUrl || !anonKey || !serviceRoleKey) {
  fatal(
    `Could not parse Supabase credentials from status output:\n${output}`
  );
}

// ── Write .env.local ───────────────────────────────────────────────────────

const envContent = `# Auto-generated by scripts/setup-local.mjs — do not commit
# Supabase Local Development
NEXT_PUBLIC_SITE_URL=http://localhost:3000

NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
`;

writeFileSync(ENV_LOCAL, envContent, 'utf-8');

console.log('\n✅ Supabase local stack is running!\n');
console.log('   API URL:        ', apiUrl);
console.log('   Studio:         ', studioUrl || 'http://127.0.0.1:54353');
console.log('   Mailpit (email):', mailUrl || 'http://127.0.0.1:54354');
console.log(`\n📄 .env.local written with local credentials.`);
console.log('\n🎉 Run "npm run dev" to start the Next.js app.\n');
